swagger: '2.0'
info:
  description: Simple Blog
  version: 1.0.0
  title: Swagger Blog
tags:
  - name: article
    description: Everything about Articles
  - name: user
    description: Operations about user
schemes:
  - https
  - http
paths:
  /articles:
    get:
      tags:
        - article
      summary: Get the list of articles on the corresponding page
      description: ''
      parameters:
        - name: page
          in: query
          description: the corresponding page
          required: true
          type: string
          x-exportParamName: Page
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ArtitleList'
  '/article/{id}':
    get:
      tags:
        - article
      summary: Get the article by id
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          x-exportParamName: Id
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Artitle'
  '/article/{id}/comments':
    get:
      tags:
        - article
      summary: Get the list of comments on the article
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          x-exportParamName: Id
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CommentList'
  '/article/{id}/comment':
    post:
      tags:
        - user
      summary: Post a comment by a logined user
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
          x-exportParamName: Id
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Comment'
          x-exportParamName: Body
      responses:
        '200':
          description: OK
  /user/register:
    post:
      tags:
        - user
      summary: Register a user
      description: ''
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/User'
          x-exportParamName: Body
      responses:
        '200':
          description: OK
  /user/login:
    post:
      tags:
        - user
      summary: Register a user
      description: ''
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/User'
          x-exportParamName: Body
      responses:
        '200':
          description: OK
definitions:
  Artitle:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      username:
        type: string
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Tag'
      date:
        type: string
        format: date
      content:
        type: string
    example:
      date: '2000-01-23'
      content: content
      id: 0
      title: title
      username: "myUser"
      tags:
        - name: name
          id: 6
        - name: name
          id: 6
  ArtitleList:
    type: array
    items:
      $ref: '#/definitions/Artitle'
  Comment:
    type: object
    properties:
      user:
        type: string
      artitle_id:
        type: integer
        format: int64
      date:
        type: string
        format: date
      cotent:
        type: string
  CommentList:
    type: array
    items:
      $ref: '#/definitions/Comment'
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
    example:
      name: name
      id: 6
  User:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
        format: password
